version: '2.1'

services:
  jefex7:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctspublic.azurecr.io/labs/jefex7
    ports:
      - $SERVER_PORT:$SERVER_PORT
